services:
  home-station-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: home-station-server
    restart: always
    expose:
      - "8080"
    environment:
      - PORT=8080
      - SERIAL_PORT=/dev/ttyACM0
      - BAUD_RATE=115200
      - LOG_LEVEL=INFO
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
